In [52]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [53]:
df=pd.read_csv("/content/Churn_Modelling.csv")

In [54]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [56]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [57]:
from sklearn.preprocessing import LabelEncoder

In [58]:
le=LabelEncoder()

In [59]:
x=df.iloc[:,3:-1].values
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [60]:
y=df.iloc[:,-1].values
y

array([1, 0, 1, ..., 1, 1, 0])

In [61]:
x[:,2]=le.fit_transform(x[:,2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [62]:
from sklearn.compose import ColumnTransformer 


In [63]:
from sklearn.preprocessing import OneHotEncoder

In [64]:
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder='passthrough')

In [65]:
x=np.array(ct.fit_transform(x))
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [66]:
from sklearn.model_selection import train_test_split

In [67]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [68]:
from sklearn.preprocessing import StandardScaler

In [69]:
import tensorflow as tf

In [70]:
std=StandardScaler()

In [71]:
x_train=std.fit_transform(x_train)

In [72]:
ann=tf.keras.models.Sequential()

In [73]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

In [74]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [75]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
235/235 [==============================] - 1s 2ms/step - loss: 0.5764 - accuracy: 0.7247
Epoch 2/100
235/235 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7977
Epoch 3/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4497 - accuracy: 0.7979
Epoch 4/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4337 - accuracy: 0.7992
Epoch 5/100
235/235 [==============================] - 1s 2ms/step - loss: 0.4196 - accuracy: 0.8072
Epoch 6/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4060 - accuracy: 0.8231
Epoch 7/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3927 - accuracy: 0.8340
Epoch 8/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3808 - accuracy: 0.8413
Epoch 9/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3698 - accuracy: 0.8473
Epoch 10/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3615 - accura

In [76]:
x_train = std.fit_transform(x_train)
x_test = std.transform(x_test)

In [77]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

79/79 [==============================] - 0s 1ms/step
[[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 1]
 [1 1]]


In [78]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [79]:
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 732 1248]
 [ 120  400]]


0.4528